unsecured:
  url: http://localhost:8081

keycloak:
  host: localhost
  port: 8180
  realm: sample-realm
  issuer-uri: http://${keycloak.host}:${keycloak.port}/auth/realms/${keycloak.realm}

secured:
  url: http://localhost:8083

spring:
  security:
    oauth2:
      client:
        registration:
          sample-client:
            provider: keycloak
            client-id: sample-client
            client-secret: 165745e9-7591-42ef-b3dc-3cef0b8b01ec
            authorization-grant-type: client_credentials
            scope: roles
        provider:
          keycloak:
            authorization-uri: ${keycloak.issuer-uri}/protocol/openid-connect/auth
            token-uri: ${keycloak.issuer-uri}/protocol/openid-connect/token