# Server port
server:
  port: 8083

# Keycloak specific properties that we will use
keycloak:
  host: localhost
  port: 8180
  realm: sample-realm
  client-id: sample-api

rest:
  security:
    issuer-uri: http://${keycloak.host}:${keycloak.port}/auth/realms/${keycloak.realm}

spring:
  jpa.open-in-view: false
  security:
    oauth2:
      resourceserver:
          jwt:
            jwk-set-uri: ${rest.security.issuer-uri}/protocol/openid-connect/certs
