# Server port
server:
  port: 8083

# Keycloak specific properties that we will use
keycloak:
  host: localhost
  port: 8180
  realm: sample-realm
  client-id: sample-api

rest:
  security:
    # Can be set to false to disable security during local development
    enabled: true
    api-matcher: /api/**
    cors:
      allowed-origins: \*
      allowed-headers: \*
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600
    issuer-uri: http://${keycloak.host}:${keycloak.port}/auth/realms/${keycloak.realm}

spring:
  jpa.open-in-view: false
  security:
    oauth2:
      resourceserver:
          jwt:
            jwk-set-uri: ${rest.security.issuer-uri}/protocol/openid-connect/certs
